controller:
  deployment:
    istioGateway: 
      enabled: true
      # optional section to configure istio to terminate HTTPS
      tlsServer: 
      - tls:
          credentialName: wc-ihc-dt-cluster-3-de-tls
          mode: SIMPLE
        port:
          name: https
          number: 443
          protocol: HTTPS
        hosts:
        - '*.ihc-dt.example.com'
