deployment:
  controllerName: oda-controller-ingress
  compconImage: tmforumodacanvas/component-istio-controller:0.4.0
  imagePullPolicy: IfNotPresent
  istioGateway: 
    enabled: true
    # optional section to configure istio gateway with wildcard certificate for HTTPS termination 
    #tlsServer: 
    #- tls:
    #    credentialName: wc-ihc-dt-example-com-tls
    #    mode: SIMPLE
    #  port:
    #    name: https
    #    number: 443
    #    protocol: HTTPS
    #  hosts:
    #  - '*.ihc-dt.example.com'
  secconImage: tmforumodacanvas/security-listener:0.6.0
  monitoredNamespaces: 'components'           # comma separated list of namespaces
  ingressClass:
    enabled: false
    name: nginx
  keycloak:
    port: 8080
#We reuse the admin user created on keycloak instalation
credentials:
  user: admin
  pass: adpass
configmap:
  #kcbase: http://canvas-keycloak:8088/auth # trying to parameterise this in the configmap
  kcrealm: myrealm
  loglevel: '20'
