{{ if .Values.deployment.istioGateway.enabled }}
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: component-gateway
  namespace: {{ .Values.deployment.monitoredNamespaces }}
spec:
  selector:
    istio: ingressgateway # use istio default controller
  servers:
  - port:
      number: 80
      name: http
      protocol: HTTP
    hosts:
    - "*"
{{- if (.Values.deployment.istioGateway.tlsServer) }}
  {{- toYaml .Values.deployment.istioGateway.tlsServer | nindent 2 }}
{{- end }}
{{ end }}