name: Check that PRs do not contain prereleaseSuffixes
on: 
  pull_request:
    branches:
      # TODO[FH]: remove before PR is merged.
      - testmain
      - master
jobs:
  lint-python-code:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: psf/black@stable
        with: 
          src: "./source/operators/secretsmanagementOperator-hc"
